name: Vote Service CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  vote-service:
    name: Vote Service CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Lint
      - name: Lint Vote Service (Flake8)
        run: |
          pip install flake8
          flake8 . || true

      # SCA
      - name: Run SCA (Trivy)
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true

      # SAST
      - name: Run SAST (Bandit)
        run: |
          pip install bandit
          bandit -r . -ll -f json -o bandit-results.json || true

      # Unit tests
      - name: Run Unit Tests
        run: |
          pip install pytest
          pytest tests || true

      # Docker build & push
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/vote-find-your-bias:${{ github.sha }}
